### ISSUE TITLE
not compatible with latest osmnx

### ISSUE THREAD

**Issue by dwastbergRSE** [AtelierLibre/osmuf#1]
Osmnx seems to have renamed and moved a number of methods used in osmuf, for example `save_and_show` is now `_save_and_show`, `make_str` no longer seems to exists and bbox_from_point has been moved to different module.  The last supported version of osmnx seems to be 0.12 so perhaps the documentation should be updated to reflect this.

**Comment by AtelierLibre** [comment]
Apologies for not picking this up before - as you might have noticed you are the first person to raise an issue or a pull request and I hadn't realised it was there! Thanks for that. I'll have a look at what you have done. You are right, OSMnx is going through quite a few changes at the moment. Can I ask what you are using OSMuf for? Thanks for your input!

**Comment by AtelierLibre** [comment]
As in the comment on the pull request, thanks again!
